name: BoomRod
version: 1.0
main: io.github.mrbeezwax.boomrod.BoomRod
author: mrbeezwax
description: A simple plugin that gives a BoomRod. Right-clicking with a BoomRod will create a harmless explosion at the crosshair.

commands:
  BoomRod:
    description: Gives the player a BoomRod
    permission: boomrod.boomrod
    permission-message: You do not have permission to /boomrod
    usage: /<command>

permissions:
  boomrod.boomrod:
    description: Gives access to the /boomrod command
    default: op